name: "Close Invalid Issue"
on:
  schedule:
  - cron: "*/6 * * * *"

permissions:
  contents: read

jobs:
  stale:
    permissions:
      issues: write  # for actions/stale to close stale issues
      pull-requests: write  # for actions/stale to close stale PRs
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
    - name: Close Stale Issues
      uses: actions/stale@v6
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: "This issue has been marked as invalid question, please give more information by following the `issue` template. The issue will be closed in 30 days if no further activity occurs."
        stale-issue-label: "invalid issue"
        days-before-stale: 0
        days-before-close: 30
        remove-stale-when-updated: true
        only-labels: "invalid issue"
